if __name__ == '__main__':
    import argparse
    import sys
    import subprocess
    from argparse import RawTextHelpFormatter

    parse = argparse.ArgumentParser(description="The predict module for predicting a input file with a trained SVM classifier.",
                                    formatter_class=RawTextHelpFormatter)

    parse.add_argument('inputfile',
                       help="The input feature vectors file, in LIBSVM format.")
    parse.add_argument('-m',
                       help="The name of trained model generated by using 'train.py'.")
    parse.add_argument('-labels',
                       help="The real label file. Optional.")
    parse.add_argument('-o',
                       help="The output file name listing the predicted labels.\n"
                       "The default name is 'output_labels.txt'.")

    args = parse.parse_args()
    sys.dont_write_bytecode = True
    cmder = ' '.join(sys.argv[1:])
    cmd = 'python predictt.pyc' + ' ' + cmder
    subprocess.call(cmd, shell=True)